### ISSUE TITLE
error TS6053: File .../typings/tsd.d.ts not found

### ISSUE THREAD

**Issue by mtpultz** [Semigradsky/math-interval-parser#2]
Installed `i18n-node`, which has `math-interval-parser` as a dependency, and this error is thrown preventing transpiling `error TS6053: File .../node_modules/math-interval-parser/typings/tsd.d.ts' not found`.  I'm not sure why this is happening, but his error seems to be related to the `/// <reference path="../typings/tsd.d.ts" />`, and seems like it is commonly fixed by adjusting the path.

**Comment by Semigradsky** [comment]
@mtpultz  `tsd` was removed on `2.0.0` version
