### ISSUE TITLE
npm error

### ISSUE THREAD

**Issue by rockyou9000** [Semigradsky/math-interval-parser#3]
in ./~/_xregexp@3.2.0@xregexp/xregexp-all.js
Critical dependencies:
1:480-487 This seems to be a pre-built javascript file. Though this is possible, it's not recommended. Try to require the original source to get
better results.

can you update xregexp to 4+ ?

**Comment by Semigradsky** [comment]
@rockyou9000 sorry for realy long response. I will do it after holidays.

**Comment by Semigradsky** [comment]
@rockyou9000 I have removed `xregexp` from dependencies.
